PredictionNum: 40  # forward predict steps
StateNum: 7   # state numbers / here: 1: x, 2: y, 3: psi, 4: v, 5: psi 6: ctex, 7: ctey, 8: epsi
ControlNum: 2  # actuator numbers /here: 1: steering angle, 2: throttle
start:
  - -1.  # x end
  - 1. # y end
  - 0. # theta end
  - 0.  # v end
  - 0.  # psi end
goal: # goal with angle
  - 2.  # x end
  - 4.5 # y end
  - 0. # theta end
  - 0.  # v end
  - 0.  # psi end
  - 0. # acc end
dt: 0.1
Lf: 1.0
ref_v: 0.5
wg:
  - 0.00001
  - 0.0001
  - 0.001
  - 0.01
  - 0.1
  - 1.
uj_bound:
  - -4.
  - 4.
uo_bound:
  - -15.
  - 15.


