base: 2.0
LF: 3.0
LB: 1.0
W: 2.0

start:
  - 5.  # x end   - -7.5  # x end
  - 4.5 # y end - 7.5 # y end
  - 60. # theta end - 0. # theta end
goal: # goal with angle
  - 16.5  # x end - -0.8  # x end
  - 50. # y end - 1.5 # y end
  - 0. # theta end   - 90. # theta end
ref_v: 1.5
dt: 0.1
wg:
  - 0.00001
  - 0.0001
  - 0.001
  - 0.01
  - 0.1
  - 1.
uj_bound:
  - -3.
  - 3.
uo_bound:
  - -10.
  - 10.


