base: 0.4
LF: 0.6
LB: 0.2
W: 0.6

start:
  - 0.5  # x end
  - 2.2 # y end
  - 0. # theta end
goal: # goal with angle
  - 3.1  # x end
  - 1.0 # y end
  - 90. # theta end
ref_v: 1.5
dt: 0.1
wg:
  - 0.00001
  - 0.0001
  - 0.001
  - 0.01
  - 0.1
  - 1.
uj_bound:
  - -3.
  - 3.
uo_bound:
  - -10.
  - 10.


