base: 1.0
LF: 1.5
LB: 0.5
W: 0.8
use_model_type: car
start:
  - 0.  # x end   - -7.5  # x end
  - 3. # y end - 7.5 # y end
  - 90. # theta end - 0. # theta end
goal: # goal with angle
  - 3.9 # x end - -0.8  # x end
  - 0. # y end - 1.5 # y end
  - 180. # theta end   - 90. # theta end
ref_v: 1.5
dt: 0.1
wg:
  - 0.00001
  - 0.0001
  - 0.001
  - 0.01
  - 0.1
  - 1.
uj_bound:
  - -3.
  - 3.
uo_bound:
  - -10.
  - 10.


