PredictionNum: 40  # forward predict steps
StateNum: 7   # state numbers / here: 1: x, 2: y, 3: psi, 4: v, 5: psi 6: ctex, 7: ctey, 8: epsi
ControlNum: 2  # actuator numbers /here: 1: steering angle, 2: throttle
start:
  - 0.  # x end
  - 0. # y end
  - 0. # theta end
  - 0.  # v end
  - 0.  # psi end
goal: # goal with angle
  - 3.  # x end
  - 4. # y end
  - 60. # theta end
  - 0.  # v end
  - 0.  # psi end
dt: 0.1
Lf: 1.0
ref_v: 15.
wg:
  - 1.
  - 10.
  - 100.
  - 12000.
  - 250000.
  - 1000000.
ua_bound:
  - -4.
  - 4.
uo_bound:
  - -25.
  - 25.


